# Generated by Django 5.1.1 on 2024-10-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_duration_meeting_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_time',
        ),
    ]
